// This file is generated by scripts/gen_enum_interfaces

export type ProductType =
    | "skill_lv_up_ticket"
    | "produce_idol_piece"
    | "support_character_piece"

export type NaviType =
    | "skill_lv_up"
    | "limit_break"
    | "master_training"

export type LiveSkillType =
    | "score_up"
    | "recovery"
    | "judgment_enhancement"
    | "combo_bonus"
    | "perfect_score_up"
    | "money_drop_up"
    | "perfect_judgment_enhancement"
    | "idol_base_exp_up"
    | "fan_up"
    | "dearness_up"
    | "bonus_reward"
    | "long_score_up"

export type Rarity =
    | "R"

export type GoodScheduleDetailType =
    | "vocal_lesson"
    | "shopping_cd"
    | "working_radio"
    | "shopping_boutique"
    | "working_model"
    | "special_lesson"